"""Markdown projection of the memory store.

Renders ``data/wiki/`` as a browsable Obsidian/VS Code-friendly tree:

    data/wiki/
    ├── index.md             # catalog of every page (Karpathy-style)
    ├── log.md               # chronological append-only timeline
    ├── entries/<id>.md      # one page per memory entry
    ├── files/<safe>.md      # per-source-file aggregation
    └── conflicts.md         # all detected conflicts in one page

The markdown layer is *derived* — it can be regenerated at any time from
``memory.json``, ``activity_log.json`` and ``conflicts.json``.  The JSON
remains the source of truth.
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

WIKI_DIRNAME = "wiki"
ENTRIES_DIR = "entries"
FILES_DIR = "files"

INDEX_FILE = "index.md"
LOG_FILE = "log.md"
CONFLICTS_FILE = "conflicts.md"

_TYPE_ICON: Dict[str, str] = {
    "bug_fix": "🐛",
    "feature": "✨",
    "decision": "🧭",
    "note": "📝",
}

_STATUS_ICON: Dict[str, str] = {
    "active": "🟢",
    "resolved": "✅",
    "conflict": "⚠️",
}


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _slug(text: str) -> str:
    """Filesystem-safe slug for arbitrary file paths."""
    text = re.sub(r"[\\/]", "__", text)
    text = re.sub(r"[^A-Za-z0-9_.-]", "_", text)
    return text.strip("_") or "unnamed"


def _short_date(iso: str) -> str:
    if not iso:
        return ""
    try:
        return iso.split("T", 1)[0]
    except Exception:
        return iso


def _short_summary(entry: Dict[str, Any], limit: int = 80) -> str:
    desc = (entry.get("description") or "").strip()
    desc = " ".join(desc.split())  # collapse whitespace
    if len(desc) > limit:
        desc = desc[: limit - 1].rstrip() + "…"
    return desc


# ── individual page renderers ────────────────────────────────────────────────

def render_entry_page(entry: Dict[str, Any]) -> str:
    eid = entry.get("id", "")
    typ = entry.get("type", "note")
    status = entry.get("status", "active")
    icon = _TYPE_ICON.get(typ, "📝")
    s_icon = _STATUS_ICON.get(status, "")

    lines: List[str] = [
        f"# {icon} {entry.get('description', '(no description)')}",
        "",
        "## Metadata",
        f"- **ID**: `{eid}`",
        f"- **Type**: `{typ}`",
        f"- **Status**: {s_icon} `{status}`",
        f"- **Confidence**: `{entry.get('confidence', 0.0)}`",
        f"- **Created**: `{entry.get('timestamp', '')}`",
    ]

    tags = entry.get("tags") or []
    if tags:
        lines.append(f"- **Tags**: {', '.join(f'`{t}`' for t in tags)}")

    lines.append("")

    # Body sections
    if entry.get("cause"):
        lines += ["## Cause", entry["cause"].strip(), ""]
    if entry.get("fix"):
        lines += ["## Fix", entry["fix"].strip(), ""]

    files = entry.get("files") or []
    if files:
        lines.append("## Affected Files")
        for f in files:
            lines.append(f"- [[files/{_slug(f)}|{f}]]")
        lines.append("")

    conflicts = entry.get("conflicts_with") or []
    if conflicts:
        lines.append("## Conflicts With")
        for cid in conflicts:
            lines.append(f"- [[entries/{cid}]]")
        lines.append("")

    lines += [
        "---",
        f"*Auto-generated by AI Memory System on {_now()}.*",
        "",
    ]
    return "\n".join(lines)


def render_file_page(file_path: str, entries: List[Dict[str, Any]]) -> str:
    lines: List[str] = [
        f"# 📂 `{file_path}`",
        "",
        f"_{len(entries)} memory entry/entries reference this file._",
        "",
        "| ID | Type | Status | Description |",
        "| -- | ---- | ------ | ----------- |",
    ]
    for e in sorted(entries, key=lambda x: x.get("timestamp", ""), reverse=True):
        eid = e.get("id", "")
        typ = e.get("type", "note")
        status = e.get("status", "active")
        lines.append(
            f"| [[entries/{eid}\\|{eid}]] "
            f"| {_TYPE_ICON.get(typ, '')} {typ} "
            f"| {_STATUS_ICON.get(status, '')} {status} "
            f"| {_short_summary(e)} |"
        )
    lines += ["", f"*Generated {_now()}*", ""]
    return "\n".join(lines)


def render_index(memory: List[Dict[str, Any]]) -> str:
    """Karpathy-style catalog: every page on one line."""
    lines: List[str] = [
        "# 🧠 Memory Index",
        "",
        f"_{len(memory)} entries · auto-generated {_now()}_",
        "",
        "## By Type",
        "",
    ]

    by_type: Dict[str, List[Dict[str, Any]]] = {}
    for e in memory:
        by_type.setdefault(e.get("type", "note"), []).append(e)

    for typ in sorted(by_type.keys()):
        icon = _TYPE_ICON.get(typ, "📝")
        lines.append(f"### {icon} {typ} ({len(by_type[typ])})")
        lines.append("")
        for e in sorted(
            by_type[typ], key=lambda x: x.get("timestamp", ""), reverse=True
        ):
            eid = e.get("id", "")
            s_icon = _STATUS_ICON.get(e.get("status", "active"), "")
            date = _short_date(e.get("timestamp", ""))
            summary = _short_summary(e)
            lines.append(f"- {s_icon} `{date}` [[entries/{eid}]] — {summary}")
        lines.append("")

    # File index
    by_file: Dict[str, int] = {}
    for e in memory:
        for f in e.get("files") or []:
            by_file[f] = by_file.get(f, 0) + 1
    if by_file:
        lines += ["## By File", ""]
        for f in sorted(by_file.keys()):
            lines.append(f"- [[files/{_slug(f)}|{f}]] _({by_file[f]})_")
        lines.append("")

    # Status overview
    by_status: Dict[str, int] = {}
    for e in memory:
        s = e.get("status", "active")
        by_status[s] = by_status.get(s, 0) + 1
    lines += ["## Status Overview", ""]
    for s, n in sorted(by_status.items()):
        lines.append(f"- {_STATUS_ICON.get(s, '')} `{s}` — **{n}**")
    lines += ["", "## Special Pages", "",
              "- [[log|Activity Log]]",
              "- [[conflicts|Conflicts]]",
              ""]
    return "\n".join(lines)


def render_log(activity: List[Dict[str, Any]]) -> str:
    lines: List[str] = [
        "# 🕒 Activity Log",
        "",
        f"_{len(activity)} events · append-only · generated {_now()}_",
        "",
    ]
    # Reverse chronological for readability
    for ev in sorted(
        activity, key=lambda x: x.get("timestamp", ""), reverse=True
    ):
        ts = ev.get("timestamp", "")
        action = ev.get("action", "?")
        affected = ev.get("affected") or []
        reason = ev.get("reason", "")
        affected_links = ", ".join(
            f"[[entries/{a}|{a}]]" for a in affected if a
        )
        lines.append(
            f"## [{ts}] {action}"
        )
        if affected_links:
            lines.append(f"- **affected**: {affected_links}")
        if reason:
            lines.append(f"- **reason**: {reason}")
        lines.append("")
    return "\n".join(lines)


def render_conflicts_page(
    conflicts: List[Dict[str, Any]], memory_index: Dict[str, Dict[str, Any]]
) -> str:
    lines: List[str] = [
        "# ⚠️ Conflicts",
        "",
        f"_{len(conflicts)} conflict(s) detected · generated {_now()}_",
        "",
    ]
    if not conflicts:
        lines += ["_No conflicts found._", ""]
        return "\n".join(lines)

    lines += [
        "| When | Similarity | Entry A | Entry B | Reason |",
        "| ---- | ---------- | ------- | ------- | ------ |",
    ]
    for c in sorted(conflicts, key=lambda x: x.get("timestamp", ""), reverse=True):
        a_id = c.get("entry_a", "")
        b_id = c.get("entry_b", "")
        a = memory_index.get(a_id, {})
        b = memory_index.get(b_id, {})
        lines.append(
            f"| {_short_date(c.get('timestamp', ''))} "
            f"| {c.get('similarity', 0.0):.2f} "
            f"| [[entries/{a_id}\\|{_short_summary(a, 40) or a_id}]] "
            f"| [[entries/{b_id}\\|{_short_summary(b, 40) or b_id}]] "
            f"| {c.get('reason', '')} |"
        )
    lines.append("")
    return "\n".join(lines)


# ── orchestration ────────────────────────────────────────────────────────────

class WikiRenderer:
    """Renders the entire markdown projection from JSON data files."""

    def __init__(self, data_dir: str | Path):
        self.data_dir = Path(data_dir)
        self.wiki_dir = self.data_dir / WIKI_DIRNAME

    def _read(self, name: str, default: Any) -> Any:
        path = self.data_dir / name
        if not path.exists():
            return default
        try:
            with path.open("r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return default

    def _write(self, rel_path: str, content: str) -> Path:
        target = self.wiki_dir / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return target

    def render_all(self) -> Dict[str, Any]:
        """Regenerate the entire wiki/ folder.  Returns a small report."""
        memory: List[Dict[str, Any]] = self._read("memory.json", [])
        activity: List[Dict[str, Any]] = self._read("activity_log.json", [])
        conflicts: List[Dict[str, Any]] = self._read("conflicts.json", [])

        self.wiki_dir.mkdir(parents=True, exist_ok=True)

        memory_index = {e.get("id", ""): e for e in memory if e.get("id")}

        # entries/<id>.md
        entries_written = 0
        for e in memory:
            eid = e.get("id")
            if not eid:
                continue
            self._write(f"{ENTRIES_DIR}/{eid}.md", render_entry_page(e))
            entries_written += 1

        # files/<slug>.md
        by_file: Dict[str, List[Dict[str, Any]]] = {}
        for e in memory:
            for f in e.get("files") or []:
                by_file.setdefault(f, []).append(e)

        files_written = 0
        for fpath, entries in by_file.items():
            self._write(
                f"{FILES_DIR}/{_slug(fpath)}.md",
                render_file_page(fpath, entries),
            )
            files_written += 1

        # top-level pages
        self._write(INDEX_FILE, render_index(memory))
        self._write(LOG_FILE, render_log(activity))
        self._write(
            CONFLICTS_FILE, render_conflicts_page(conflicts, memory_index)
        )

        return {
            "wiki_dir": str(self.wiki_dir),
            "entries_pages": entries_written,
            "file_pages": files_written,
            "log_events": len(activity),
            "conflicts": len(conflicts),
            "rendered_at": _now(),
        }
