# ${project_name} — Copilot Instructions
<!-- Auto-generated by AI Memory System on ${generated_at} -->

## Project Overview
- **Project**: ${project_name}
- **Language**: ${language}
- **Framework**: ${framework}

## Coding Standards
- Follow existing code style and naming conventions.
- Prefer clear, readable code over clever one-liners.
- Use meaningful variable and function names; keep functions small and focused.
- Write tests for all new functionality.
- Keep commits small and focused on a single change.

## Patterns and Conventions
- Document all public APIs with docstrings or JSDoc comments.
- Validate inputs at system boundaries; trust nothing from outside.
- Avoid silent failures — raise, log, or surface errors explicitly.
- Prefer composition over inheritance.
- Avoid premature optimisation; profile before tuning.

${extra_instructions}

## Agent Workflow — Memory Recording

After every file edit (create, modify, delete), **run this command in the terminal**:

```powershell
c:/python313/python.exe C:/ai_memory_system/run.py --project ${project_name} add_memory `
  --type <bug_fix|feature|decision|note> `
  --description "<one sentence: what was done and why>" `
  --cause "<what triggered the change>" `
  --fix "<what exactly changed and in which file>" `
  --files <space-separated relative file paths> `
  --confidence 0.8 `
  --tags agent auto
```

Rules for filling the fields:
- `--project`: name of the current project (`${project_name}`). Always include it.
- `--type`: `bug_fix` if fixing an error; `feature` if adding new behavior; `decision` if choosing between alternatives; `note` otherwise.
- `--description`: copy the user's prompt, condensed to one sentence.
- `--files`: relative paths from the project root (e.g. `core/engine.py`).
- Do **not** skip this step — it is the project's persistent memory.

After `add_memory`, also run:

```powershell
c:/python313/python.exe C:/ai_memory_system/run.py --project ${project_name} render_wiki
```

> The `PostToolUse` hook (`memory.json`) runs `hook_handler.py` automatically.  
> Use the manual command above when the hook is not active or for richer metadata.

## Learned Patterns
<!-- This section is auto-updated by the AI Memory System learner. -->

